version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PASSWORD=root
      - DB_NAME=miniproject
      - DB_PORT=3306
    ports:
      - 8081:8081
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=miniproject
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
